version: '3.1'
services:
  jenkins:
    container_name: jenkins
    build: ./jenkins
    image: jenkins
    ports:
      - "80:8080"
      - "50000:50000"
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - 'JAVA_OPTS="-Djenkins.install.runSetupWizard=false"'
      - JENKINS_ADMIN_USERNAME=$JENKINS_ADMIN_USERNAME
      - JENKINS_ADMIN_PASSWORD=$JENKINS_ADMIN_PASSWORD
